import Header from "../components/Header/Header";
import Head from "next/head";
import styled from "styled-components";

const dev = process.env.NODE_ENV !== "production";
export const serverUrl = dev
  ? "http://localhost:3000"
  : "https://gonzalo.vercel.app";

const Main = styled.main`
  height: 100%;
`;
const Body = styled.body`
  background-repeat: no-repeat;
  background-size: cover;
  &:before {
    backdrop-filter: blur(10px);
    -webkit-backdrop-filter: blur(10px);
    content: "";
    position: fixed;
    left: 0;
    width: 100vw;
    height: 100vh;
    background: url(${(props) => props.theme.bg});
    background-size: cover;
    background-position: 100% 6%;
    
    transform: scale(1.3);
    z-index: -1;
  }
`;
const Box = styled.div`
  position: absolute;
  top: 0%;
  left: 10%;
  width: 600px;
  height: 600px;
  background-image: radial-gradient(
    closest-side,
    rgb(45, 212, 191),
    rgba(233, 168, 2, 0)
  );

  z-index: -1;
`;
const Layout = ({ onToggleTheme, children }) => {
  const changeFixedScroll = (e) => { };
  return (
    <div>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <title>Create Next Gonzalo Valdez</title>
      </Head>

      <Body onScroll={changeFixedScroll} id="body">
        <div className="bg">
          <Header onToggleTheme={onToggleTheme} />
          <Main>{children}</Main>
          <div id="modal-root"></div>
        </div>
      </Body>
    </div>
  );
};

export default Layout;
